//! Directives that are Linux-kernel-only and rejected with a warning.
//!
//! These are recognised so unit files round-trip cleanly through `cat`/`show`
//! but they have no behavioural effect under SystemL on macOS. Phase 4 may
//! best-effort some of them via `sandbox-exec`.

/// Directives keyed by `(section, key)`. Lookup is case-sensitive — systemd
/// directive names are camel-case and stable.
#[must_use]
pub fn is_linux_only(section: &str, key: &str) -> bool {
    matches!(
        (section, key),
        // ----- cgroup resource control (man systemd.resource-control) -----
        ("Service" | "Scope" | "Slice", "CPUAccounting")
        | ("Service" | "Scope" | "Slice", "CPUWeight")
        | ("Service" | "Scope" | "Slice", "StartupCPUWeight")
        | ("Service" | "Scope" | "Slice", "CPUQuota")
        | ("Service" | "Scope" | "Slice", "CPUQuotaPeriodSec")
        | ("Service" | "Scope" | "Slice", "AllowedCPUs")
        | ("Service" | "Scope" | "Slice", "StartupAllowedCPUs")
        | ("Service" | "Scope" | "Slice", "MemoryAccounting")
        | ("Service" | "Scope" | "Slice", "MemoryMin")
        | ("Service" | "Scope" | "Slice", "MemoryLow")
        | ("Service" | "Scope" | "Slice", "MemoryHigh")
        | ("Service" | "Scope" | "Slice", "MemoryMax")
        | ("Service" | "Scope" | "Slice", "MemoryLimit")
        | ("Service" | "Scope" | "Slice", "MemorySwapMax")
        | ("Service" | "Scope" | "Slice", "MemoryZSwapMax")
        | ("Service" | "Scope" | "Slice", "TasksAccounting")
        | ("Service" | "Scope" | "Slice", "TasksMax")
        | ("Service" | "Scope" | "Slice", "IOAccounting")
        | ("Service" | "Scope" | "Slice", "IOWeight")
        | ("Service" | "Scope" | "Slice", "StartupIOWeight")
        | ("Service" | "Scope" | "Slice", "IODeviceWeight")
        | ("Service" | "Scope" | "Slice", "IOReadBandwidthMax")
        | ("Service" | "Scope" | "Slice", "IOWriteBandwidthMax")
        | ("Service" | "Scope" | "Slice", "IOReadIOPSMax")
        | ("Service" | "Scope" | "Slice", "IOWriteIOPSMax")
        | ("Service" | "Scope" | "Slice", "IODeviceLatencyTargetSec")
        | ("Service" | "Scope" | "Slice", "BlockIOAccounting")
        | ("Service" | "Scope" | "Slice", "BlockIOWeight")
        | ("Service" | "Scope" | "Slice", "BlockIODeviceWeight")
        | ("Service" | "Scope" | "Slice", "BlockIOReadBandwidth")
        | ("Service" | "Scope" | "Slice", "BlockIOWriteBandwidth")
        | ("Service" | "Scope" | "Slice", "IPAccounting")
        | ("Service" | "Scope" | "Slice", "IPAddressAllow")
        | ("Service" | "Scope" | "Slice", "IPAddressDeny")
        | ("Service" | "Scope" | "Slice", "IPIngressFilterPath")
        | ("Service" | "Scope" | "Slice", "IPEgressFilterPath")
        | ("Service" | "Scope" | "Slice", "DeviceAllow")
        | ("Service" | "Scope" | "Slice", "DevicePolicy")
        | ("Service" | "Scope" | "Slice", "Slice")
        | ("Service" | "Scope" | "Slice", "Delegate")
        | ("Service" | "Scope" | "Slice", "DelegateSubgroup")
        | ("Service" | "Scope" | "Slice", "DisableControllers")
        | ("Service" | "Scope" | "Slice", "ManagedOOMSwap")
        | ("Service" | "Scope" | "Slice", "ManagedOOMMemoryPressure")
        | ("Service" | "Scope" | "Slice", "ManagedOOMMemoryPressureLimit")
        | ("Service" | "Scope" | "Slice", "ManagedOOMPreference")
        | ("Service", "OOMPolicy")
        | ("Service", "OOMScoreAdjust")

        // ----- namespacing -----
        | ("Service", "PrivateTmp")
        | ("Service", "PrivateDevices")
        | ("Service", "PrivateNetwork")
        | ("Service", "NetworkNamespacePath")
        | ("Service", "PrivateIPC")
        | ("Service", "IPCNamespacePath")
        | ("Service", "PrivateUsers")
        | ("Service", "PrivateMounts")
        | ("Service", "MountFlags")
        | ("Service", "ProtectSystem")
        | ("Service", "ProtectHome")
        | ("Service", "ProtectKernelTunables")
        | ("Service", "ProtectKernelModules")
        | ("Service", "ProtectKernelLogs")
        | ("Service", "ProtectClock")
        | ("Service", "ProtectControlGroups")
        | ("Service", "ProtectHostname")
        | ("Service", "ProtectProc")
        | ("Service", "ProcSubset")
        | ("Service", "RestrictNamespaces")
        | ("Service", "BindPaths")
        | ("Service", "BindReadOnlyPaths")
        | ("Service", "ReadOnlyPaths")
        | ("Service", "ReadWritePaths")
        | ("Service", "InaccessiblePaths")
        | ("Service", "ExecPaths")
        | ("Service", "NoExecPaths")
        | ("Service", "TemporaryFileSystem")
        | ("Service", "MountAPIVFS")
        | ("Service", "MountImages")
        | ("Service", "RootImage")
        | ("Service", "RootHash")
        | ("Service", "RootHashSignature")
        | ("Service", "RootImageOptions")
        | ("Service", "RootVerity")
        | ("Service", "ExtensionDirectories")
        | ("Service", "ExtensionImages")

        // ----- capabilities / seccomp / restrictions -----
        | ("Service", "CapabilityBoundingSet")
        | ("Service", "AmbientCapabilities")
        | ("Service", "SecureBits")
        | ("Service", "NoNewPrivileges")
        | ("Service", "SystemCallFilter")
        | ("Service", "SystemCallErrorNumber")
        | ("Service", "SystemCallArchitectures")
        | ("Service", "SystemCallLog")
        | ("Service", "RestrictAddressFamilies")
        | ("Service", "RestrictFileSystems")
        | ("Service", "RestrictNetworkInterfaces")
        | ("Service", "RestrictRealtime")
        | ("Service", "RestrictSUIDSGID")
        | ("Service", "LockPersonality")
        | ("Service", "MemoryDenyWriteExecute")
        | ("Service", "RemoveIPC")
        | ("Service", "Personality")
        | ("Service", "KeyringMode")

        // ----- MAC frameworks (Linux-only) -----
        | ("Service", "SELinuxContext")
        | ("Service", "AppArmorProfile")
        | ("Service", "SmackProcessLabel")

        // ----- DynamicUser / PAM -----
        | ("Service", "DynamicUser")
        | ("Service", "PAMName")

        // ----- Audit -----
        | ("Service", "AuditMessage")
    )
}

/// Directives that we deliberately accept verbatim and round-trip — no
/// behaviour change but useful for `cat` / `show` faithfulness.
#[must_use]
pub fn is_known_passthrough(section: &str, key: &str) -> bool {
    matches!(
        (section, key),
        ("Service", "TTYPath")
            | ("Service", "TTYReset")
            | ("Service", "TTYVHangup")
            | ("Service", "TTYVTDisallocate")
            | ("Service", "TTYColumns")
            | ("Service", "TTYRows")
            | ("Service", "SyslogIdentifier")
            | ("Service", "SyslogFacility")
            | ("Service", "SyslogLevel")
            | ("Service", "SyslogLevelPrefix")
            | ("Service", "LogExtraFields")
            | ("Service", "LogFilterPatterns")
            | ("Service", "LogLevelMax")
            | ("Service", "LogNamespace")
            | ("Service", "LogRateLimitIntervalSec")
            | ("Service", "LogRateLimitBurst")
            | ("Service", "RuntimeDirectory")
            | ("Service", "RuntimeDirectoryMode")
            | ("Service", "RuntimeDirectoryPreserve")
            | ("Service", "StateDirectory")
            | ("Service", "StateDirectoryMode")
            | ("Service", "CacheDirectory")
            | ("Service", "CacheDirectoryMode")
            | ("Service", "LogsDirectory")
            | ("Service", "LogsDirectoryMode")
            | ("Service", "ConfigurationDirectory")
            | ("Service", "ConfigurationDirectoryMode")
    )
}
